apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'org.apache.grails.gradle.grails-publish'
apply plugin: 'org.apache.grails.gradle.grails-plugin'
apply plugin: 'java-library'

group "cloud.wondrify"

ext {
  pomDescription = 'Selfie is a Grails Image / File Upload Plugin. Use Selfie to attach files to your domain models, upload to a CDN, validate content, produce thumbnails.'
  publishedProjects = [project.name]
}

configurations {
    provided
    doc.extendsFrom(runtime)
}

sourceSets {
    main {
        compileClasspath += configurations.provided
        groovy.srcDirs += ['src/main/java']
        java.srcDirs = []
    }
}

// https://github.com/apache/grails-core/issues/15321
tasks.withType(GroovyCompile).configureEach {
    groovyOptions.optimizationOptions.indy = false
}

repositories {
  mavenLocal()
  mavenCentral()
  maven {
    url = uri("https://central.sonatype.com/repository/maven-snapshots/")
  }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-logging'
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.apache.grails:grails-core"
    implementation "org.apache.grails:grails-web-boot"
    implementation "org.apache.grails:grails-databinding"
    implementation "org.apache.grails:grails-services"
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    api 'org.imgscalr:imgscalr-lib:4.2'
    api "cloud.wondrify:karman-core:$karmanVersion"
    api "cloud.wondrify:karman-grails:$karmanVersion"
    api "org.apache.grails:grails-domain-class"
    api "org.apache.grails:grails-data-hibernate5"
    testImplementation "org.apache.grails:grails-testing-support-datamapping"
    testImplementation "org.mockito:mockito-core"
    testImplementation "org.apache.grails:grails-testing-support-web"
}


apply {
    from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}